<template><div class="dashboard page-content">
  <div class="welcome"><div><span class="eyebrow">SATURDAY · 21 JUNE</span><h1>晚上好，运营同学</h1><p>今天已有 <b>328</b> 位新用户加入学徒行，旅行内容浏览量增长 <b>12.6%</b>。</p></div><div class="welcome-art"><i>行</i><span>提笔上岸<br/>收笔远行</span></div></div>
  <div class="stat-cards"><article v-for="s in stats" :key="s.name"><div class="stat-icon" :style="{background:s.bg,color:s.color}">{{s.icon}}</div><div><small>{{s.name}}</small><strong>{{s.value}}</strong><span :class="s.down?'down':''">{{s.trend}}</span></div></article></div>
  <div class="dash-grid"><section class="dash-card trend-card"><div class="card-head"><div><h3>业务增长趋势</h3><p>近 7 天访问与转化情况</p></div><div class="legend"><i></i>访问量 <i></i>转化量</div></div><div class="chart"><div class="y-axis"><span>400</span><span>300</span><span>200</span><span>100</span><span>0</span></div><div class="chart-body"><div class="grid-lines"><i v-for="n in 5" :key="n"></i></div><svg viewBox="0 0 700 240" preserveAspectRatio="none"><polyline points="0,180 116,145 232,162 348,92 464,112 580,38 700,62" fill="none" stroke="#12a594" stroke-width="5"/><polyline points="0,210 116,198 232,192 348,170 464,160 580,125 700,132" fill="none" stroke="#ff7a35" stroke-width="5"/></svg><div class="x-axis"><span v-for="d in ['15日','16日','17日','18日','19日','20日','21日']" :key="d">{{d}}</span></div></div></div></section>
  <section class="dash-card todos"><div class="card-head"><div><h3>今日待办</h3><p>优先处理影响用户体验的事项</p></div><button>全部任务</button></div><div v-for="t in todos" :key="t.name" class="todo-item"><i :style="{background:t.bg,color:t.color}">{{t.icon}}</i><div><b>{{t.name}}</b><span>{{t.desc}}</span></div><strong>{{t.count}}</strong><em>›</em></div></section></div>
  <div class="dash-grid lower"><section class="dash-card"><div class="card-head"><div><h3>首页装修状态</h3><p>小程序首页内容概览</p></div><button @click="$emit('navigate','decorator')">进入装修</button></div><div class="page-status" v-for="p in homePages" :key="p.id"><div class="page-thumb">{{p.name[0]}}</div><div><b>{{p.name}}</b><span>{{p.blocks.length}} 个组件 · {{p.path}}</span></div><span class="status" :class="p.status">{{p.status==='published'?'已发布':'草稿'}}</span></div></section>
  <section class="dash-card"><div class="card-head"><div><h3>热门旅行路线</h3><p>按本周浏览与收藏排序</p></div><button @click="$emit('navigate','routes')">管理路线</button></div><div class="hot-route" v-for="(r,i) in config.routes" :key="r.id"><span class="rank">0{{i+1}}</span><img :src="r.image"><div><b>{{r.name}}</b><span>{{r.days}} · {{r.price}} 积分</span></div><strong>{{[12860,9862,7201][i]}}</strong><small>浏览</small></div></section></div>
</div></template>
<script setup>
import { computed } from 'vue'
const props=defineProps({config:Object});defineEmits(['navigate'])
const homePages=computed(()=>props.config?.pages?.filter(page=>page.id==='home')||[])
const stats=[{name:'今日新增用户',value:'328',trend:'↑ 18.2%',icon:'人',bg:'#e8f7f3',color:'#0a8c7d'},{name:'邀请注册转化率',value:'23.8%',trend:'↑ 3.2%',icon:'邀',bg:'#fff1e7',color:'#e66727'},{name:'积分发放总量',value:'12,860',trend:'今日 +328',icon:'分',bg:'#fff8d9',color:'#a77b00'},{name:'定制需求订单',value:'1,209',trend:'本月 +168',icon:'旅',bg:'#e9efff',color:'#5475d8'},{name:'待审核订单',value:'18',trend:'较昨日 +4',down:true,icon:'审',bg:'#ffecee',color:'#d95762'}]
const todos=[{name:'泰山游预约待审核',desc:'最早申请已等待 2 小时',count:8,icon:'山',bg:'#fff1e7',color:'#e66727'},{name:'人工定制需求待分配',desc:'请分配至合作旅行社',count:6,icon:'旅',bg:'#e8f7f3',color:'#0a8c7d'},{name:'异常邀请账号待核查',desc:'存在相同设备批量注册',count:4,icon:'!',bg:'#ffecee',color:'#d95762'}]
</script>
